In [1]:
from google.colab import files
uploaded = files.upload()

Saving indian_roads_dataset.csv to indian_roads_dataset.csv


In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('indian_roads_dataset.csv')

In [4]:
df.head(5)

,accident_id,city,state,latitude,longitude,date,time,hour,day_of_week,is_weekend,...,visibility,temperature,traffic_density,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score
0,0,Pune,Maharashtra,18.680827,73.930388,2023-10-22,5:00,5,Sunday,1,...,low,32,high,weather,fatal,2,2,0,NaN,0.85
1,1,Mumbai,Maharashtra,18.817732,72.790846,2023-05-21,4:00,4,Sunday,1,...,high,34,low,weather,major,4,3,0,NaN,0.10
2,2,Mumbai,Maharashtra,19.096889,72.819424,2024-07-10,13:00,13,Wednesday,0,...,low,21,medium,weather,minor,1,1,0,NaN,0.45
3,3,Chandigarh,Punjab,30.787805,76.847507,2025-03-30,11:00,11,Sunday,1,...,low,30,high,distraction,minor,5,2,0,NaN,0.65
4,4,Chennai,Tamil Nadu,12.965155,80.283313,2024-01-25,16:00,16,Thursday,0,...,high,24,low,distraction,minor,2,1,0,NaN,0.10


In [5]:
df.shape

(20000, 24)

In [6]:
df.shape[1]

24

In [7]:
len(df)

20000

In [8]:
cause_counts = df['cause'].value_counts()
print(cause_counts)

cause
distraction      4026
overspeeding     4025
weather          3997
drunk driving    3978
poor road        3974
Name: count, dtype: int64


In [9]:
missing_value = df.isnull().sum()
print(missing_value)

accident_id              0
city                     0
state                    0
latitude                 0
longitude                0
date                     0
time                     0
hour                     0
day_of_week              0
is_weekend               0
road_type                0
lanes                    0
traffic_signal           0
weather                  0
visibility               0
temperature              0
traffic_density          0
cause                    0
accident_severity        0
vehicles_involved        0
casualties               0
is_peak_hour             0
festival             19885
risk_score               0
dtype: int64


In [10]:
df['date'] = pd.to_datetime(df['date'])
print(df['date'])

0       2023-10-22
1       2023-05-21
2       2024-07-10
3       2025-03-30
4       2024-01-25
           ...    
19995   2022-09-29
19996   2023-11-25
19997   2022-06-18
19998   2023-03-12
19999   2024-07-05
Name: date, Length: 20000, dtype: datetime64[ns]


In [11]:
df.head(5)

,accident_id,city,state,latitude,longitude,date,time,hour,day_of_week,is_weekend,...,visibility,temperature,traffic_density,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score
0,0,Pune,Maharashtra,18.680827,73.930388,2023-10-22,5:00,5,Sunday,1,...,low,32,high,weather,fatal,2,2,0,NaN,0.85
1,1,Mumbai,Maharashtra,18.817732,72.790846,2023-05-21,4:00,4,Sunday,1,...,high,34,low,weather,major,4,3,0,NaN,0.10
2,2,Mumbai,Maharashtra,19.096889,72.819424,2024-07-10,13:00,13,Wednesday,0,...,low,21,medium,weather,minor,1,1,0,NaN,0.45
3,3,Chandigarh,Punjab,30.787805,76.847507,2025-03-30,11:00,11,Sunday,1,...,low,30,high,distraction,minor,5,2,0,NaN,0.65
4,4,Chennai,Tamil Nadu,12.965155,80.283313,2024-01-25,16:00,16,Thursday,0,...,high,24,low,distraction,minor,2,1,0,NaN,0.10


In [12]:
df.describe()

,accident_id,latitude,longitude,date,hour,is_weekend,lanes,traffic_signal,temperature,vehicles_involved,casualties,is_peak_hour,risk_score
count,20000.000000,20000.000000,20000.000000,20000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,9999.500000,20.389207,78.173330,2023-08-22 07:04:48.000000256,11.487200,0.286150,3.493950,0.499850,27.579600,2.992000,1.726450,0.247400,0.437585
min,0.000000,12.800172,72.700017,2022-01-01 00:00:00,0.000000,0.000000,1.000000,0.000000,15.000000,1.000000,0.000000,0.000000,0.100000
25%,4999.750000,13.198653,73.997979,2022-10-25 00:00:00,5.000000,0.000000,2.000000,0.000000,21.000000,2.000000,1.000000,0.000000,0.250000
50%,9999.500000,18.812008,77.297000,2023-08-21 00:00:00,12.000000,0.000000,4.000000,0.000000,28.000000,3.000000,1.000000,0.000000,0.450000
75%,14999.250000,28.402467,80.111089,2024-06-21 00:00:00,18.000000,1.000000,5.000000,1.000000,34.000000,4.000000,3.000000,0.000000,0.600000
max,19999.000000,30.799960,88.499861,2025-04-15 00:00:00,23.000000,1.000000,6.000000,1.000000,40.000000,5.000000,5.000000,1.000000,1.000000
std,5773.647028,6.165791,4.485967,NaN,6.945563,0.451972,1.705406,0.500012,7.454746,1.415534,1.489104,0.431512,0.218130


In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype         
---  ------             --------------  -----         
 0   accident_id        20000 non-null  int64         
 1   city               20000 non-null  object        
 2   state              20000 non-null  object        
 3   latitude           20000 non-null  float64       
 4   longitude          20000 non-null  float64       
 5   date               20000 non-null  datetime64[ns]
 6   time               20000 non-null  object        
 7   hour               20000 non-null  int64         
 8   day_of_week        20000 non-null  object        
 9   is_weekend         20000 non-null  int64         
 10  road_type          20000 non-null  object        
 11  lanes              20000 non-null  int64         
 12  traffic_signal     20000 non-null  int64         
 13  weather            20000 non-null  object        
 14  visibi

In [14]:
df['month'] = df['date'].dt.month
print(df['month'])

0        10
1         5
2         7
3         3
4         1
         ..
19995     9
19996    11
19997     6
19998     3
19999     7
Name: month, Length: 20000, dtype: int32


In [15]:
df['day'] = df['date'].dt.day
print(df['day'])

0        22
1        21
2        10
3        30
4        25
         ..
19995    29
19996    25
19997    18
19998    12
19999     5
Name: day, Length: 20000, dtype: int32


In [16]:
df.head(5)

,accident_id,city,state,latitude,longitude,date,time,hour,day_of_week,is_weekend,...,traffic_density,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score,month,day
0,0,Pune,Maharashtra,18.680827,73.930388,2023-10-22,5:00,5,Sunday,1,...,high,weather,fatal,2,2,0,NaN,0.85,10,22
1,1,Mumbai,Maharashtra,18.817732,72.790846,2023-05-21,4:00,4,Sunday,1,...,low,weather,major,4,3,0,NaN,0.10,5,21
2,2,Mumbai,Maharashtra,19.096889,72.819424,2024-07-10,13:00,13,Wednesday,0,...,medium,weather,minor,1,1,0,NaN,0.45,7,10
3,3,Chandigarh,Punjab,30.787805,76.847507,2025-03-30,11:00,11,Sunday,1,...,high,distraction,minor,5,2,0,NaN,0.65,3,30
4,4,Chennai,Tamil Nadu,12.965155,80.283313,2024-01-25,16:00,16,Thursday,0,...,low,distraction,minor,2,1,0,NaN,0.10,1,25


In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype         
---  ------             --------------  -----         
 0   accident_id        20000 non-null  int64         
 1   city               20000 non-null  object        
 2   state              20000 non-null  object        
 3   latitude           20000 non-null  float64       
 4   longitude          20000 non-null  float64       
 5   date               20000 non-null  datetime64[ns]
 6   time               20000 non-null  object        
 7   hour               20000 non-null  int64         
 8   day_of_week        20000 non-null  object        
 9   is_weekend         20000 non-null  int64         
 10  road_type          20000 non-null  object        
 11  lanes              20000 non-null  int64         
 12  traffic_signal     20000 non-null  int64         
 13  weather            20000 non-null  object        
 14  visibi

In [18]:
categorical_calls = ['city', 'state', 'day_of_week', 'road_type', 'weather', 'visibility', 'traffic_density', 'accident_severity']

In [19]:
for i, col in enumerate(categorical_calls, 1):
  print(f"  {i}. {col}")

  1. city
  2. state
  3. day_of_week
  4. road_type
  5. weather
  6. visibility
  7. traffic_density
  8. accident_severity


In [20]:
from sklearn.preprocessing import LabelEncoder
label_encoders = {}
for col in categorical_calls:
  le = LabelEncoder()
  df[col + '_encoded'] = le.fit_transform(df[col])
  label_encoders[col] = le
  print(f"✓ Encoded {col} -> {col}_encoded")

✓ Encoded city -> city_encoded
✓ Encoded state -> state_encoded
✓ Encoded day_of_week -> day_of_week_encoded
✓ Encoded road_type -> road_type_encoded
✓ Encoded weather -> weather_encoded
✓ Encoded visibility -> visibility_encoded
✓ Encoded traffic_density -> traffic_density_encoded
✓ Encoded accident_severity -> accident_severity_encoded


In [21]:
df.head(5)

,accident_id,city,state,latitude,longitude,date,time,hour,day_of_week,is_weekend,...,month,day,city_encoded,state_encoded,day_of_week_encoded,road_type_encoded,weather_encoded,visibility_encoded,traffic_density_encoded,accident_severity_encoded
0,0,Pune,Maharashtra,18.680827,73.930388,2023-10-22,5:00,5,Sunday,1,...,10,22,7,2,3,0,1,1,0,0
1,1,Mumbai,Maharashtra,18.817732,72.790846,2023-05-21,4:00,4,Sunday,1,...,5,21,6,2,3,2,0,0,1,1
2,2,Mumbai,Maharashtra,19.096889,72.819424,2024-07-10,13:00,13,Wednesday,0,...,7,10,6,2,6,2,1,1,2,2
3,3,Chandigarh,Punjab,30.787805,76.847507,2025-03-30,11:00,11,Sunday,1,...,3,30,1,3,3,2,1,1,0,2
4,4,Chennai,Tamil Nadu,12.965155,80.283313,2024-01-25,16:00,16,Thursday,0,...,1,25,2,4,4,0,0,0,1,2


In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 34 columns):
 #   Column                     Non-Null Count  Dtype         
---  ------                     --------------  -----         
 0   accident_id                20000 non-null  int64         
 1   city                       20000 non-null  object        
 2   state                      20000 non-null  object        
 3   latitude                   20000 non-null  float64       
 4   longitude                  20000 non-null  float64       
 5   date                       20000 non-null  datetime64[ns]
 6   time                       20000 non-null  object        
 7   hour                       20000 non-null  int64         
 8   day_of_week                20000 non-null  object        
 9   is_weekend                 20000 non-null  int64         
 10  road_type                  20000 non-null  object        
 11  lanes                      20000 non-null  int64         
 12  traf

In [23]:
features = [
    'city_encoded', 'state_encoded', 'latitude', 'longitude',
    'hour', 'month', 'day', 'day_of_week_encoded', 'is_weekend', 'is_peak_hour',
    'road_type_encoded', 'lanes', 'traffic_signal',
    'weather_encoded', 'visibility_encoded', 'temperature',
    'traffic_density_encoded',
    'accident_severity_encoded', 'vehicles_involved', 'casualties', 'risk_score'
]

In [24]:
for i, feature in enumerate(features, 1):
    print(f"  {i:2d}. {feature}")

   1. city_encoded
   2. state_encoded
   3. latitude
   4. longitude
   5. hour
   6. month
   7. day
   8. day_of_week_encoded
   9. is_weekend
  10. is_peak_hour
  11. road_type_encoded
  12. lanes
  13. traffic_signal
  14. weather_encoded
  15. visibility_encoded
  16. temperature
  17. traffic_density_encoded
  18. accident_severity_encoded
  19. vehicles_involved
  20. casualties
  21. risk_score


In [25]:
target = 'cause'

In [26]:
X = df[feature]
y = df[target]

In [27]:
X.shape

(20000,)

In [28]:
y.shape

(20000,)

In [37]:
from sklearn.model_selection import train_test_split

# If you need just one feature (example):
X_train = X_train.to_frame()   # convert series to DataFrame (1 column)

# Better: keep multiple features
X = df[features]              # DataFrame shape (20000, n_features)
y = df[target]                # Series shape (20000,)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [38]:
X_train.shape

(16000, 21)

In [39]:
X_test.shape

(4000, 21)

In [40]:
y_train.shape

(16000,)

In [41]:
y_test.shape

(4000,)

In [42]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(
    n_estimators=100,      # Number of trees (experts)
    random_state=42,       # For reproducible results
    max_depth=10,          # How deep each tree can grow
    min_samples_split=5,   # Minimum samples to split a node
    min_samples_leaf=2     # Minimum samples in a leaf
)

In [43]:
model.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, min_samples_leaf=2, min_samples_split=5,
                       random_state=42)

In [44]:
y_pred = model.predict(X_test)

In [54]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.20125


In [55]:
print(classification_report(y_test, y_pred))

               precision    recall  f1-score   support

  distraction       0.19      0.23      0.21       805
drunk driving       0.20      0.18      0.19       796
 overspeeding       0.22      0.21      0.22       805
    poor road       0.20      0.18      0.19       795
      weather       0.20      0.20      0.20       799

     accuracy                           0.20      4000
    macro avg       0.20      0.20      0.20      4000
 weighted avg       0.20      0.20      0.20      4000



In [56]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[185 143 157 162 158]
 [186 140 160 144 166]
 [185 144 173 131 172]
 [205 154 139 145 152]
 [192 134 161 150 162]]


In [57]:
feature_importance = model.feature_importances_

importance_df = pd.DataFrame({
    'Feature': features,
    'Importance': feature_importance
})

In [61]:
importance_df = importance_df.sort_values('Importance', ascending=False)

for i, row in importance_df.iterrows():
    print(f"{row['Feature']}: {row['Importance']*100:.2f}%")

longitude: 12.02%
latitude: 11.91%
day: 8.69%
temperature: 8.37%
hour: 7.67%
month: 6.93%
day_of_week_encoded: 5.15%
lanes: 5.01%
risk_score: 4.63%
casualties: 4.44%
vehicles_involved: 3.87%
road_type_encoded: 2.92%
traffic_density_encoded: 2.58%
accident_severity_encoded: 2.55%
city_encoded: 2.45%
weather_encoded: 2.26%
state_encoded: 2.21%
visibility_encoded: 1.98%
traffic_signal: 1.97%
is_peak_hour: 1.22%
is_weekend: 1.17%


In [62]:
sample_predictions = pd.DataFrame({
    'Actual Cause': y_test.head(),
    'Predicted Cause': y_pred[:5]
})
print("First 5 test cases:")
print(sample_predictions)

First 5 test cases:
        Actual Cause Predicted Cause
16179  drunk driving     distraction
7084       poor road    overspeeding
13635   overspeeding   drunk driving
2420     distraction         weather
2956    overspeeding       poor road


In [64]:
#model predicts one of the 5 causes (distraction/overspeeding/weather/drunk driving/poor road) for each row in test data